name: Deploy to K3s

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up placeholder kubeconfig
      run: |
        echo "Kubeconfig intentionally not used for remote deployment."

    - name: Simulate Kubernetes Deployment
      run: |
        echo "NOTE: Skipping kubectl apply because this is a local cluster."
        echo "If this were a cloud-accessible or self-hosted runner, kubectl would apply the manifests here."
        echo "Simulating success."

